### ISSUE TITLE
Need a better description of exactly what this operator does.

### ISSUE THREAD

**Issue by ghost** [lessor/lessor#46]
Please add a list of actions this operators takes on user's behalf.

**Comment by marpaia** [comment]
This controller doesn't do much yet. [The CRD in the README](https://github.com/lessor/lessor#tenant-custom-resource) is currently accurate, you can only define tenants and list namespaces.

The main loop of the controller is implemented [right here](https://github.com/lessor/lessor/blob/0eb5dd4f9191baa4de3d7a56663b238ec76c5606/pkg/controller/synchronize.go#L11-L48). The only thing it's doing right now is creating the namespaces enumerated in the tenant CRD:

```go
	for _, namespace := range tenant.Namespaces() {
		_, err = c.namespacesLister.Get(namespace)
		switch {
		case apierrors.IsNotFound(err):
			if _, err := c.kubeClient.CoreV1().Namespaces().Create(tenant.NamespaceResource(namespace)); err != nil {
				return errors.Wrapf(err, "error creating namespace %s for tenant %s", namespace, tenant.Name)
			}
		case err != nil:
			errors.Wrapf(err, "error getting namespace %s for tenant %s", namespace, tenant.Name)
		default:
			// the namespace already exists
		}
	}
```

This is really just standing as a base for aa productive controller development repo that I've prepared while participating in the Multi-tenancy Kubernetes Working Group. While we haven't been at the stage where we need to be doing controller development, that's changing now. Check out the "S2" plan in the [https://docs.google.com/presentation/d/1dsAsVm8kCA9Dx9_gMEYeJL7pduAbnfnxT9lhbyCvHDg/edit#slide=id.p19](multi-tenancy working group planning document).

Note that, while everything I've said here is current as of Jan 29 2019, readers from the future may find many more features in Lessor.

**Comment by ghost** [comment]
Awesome answer. Thanks @marpaia !
